import {Check,Monitor,Utensils} from 'lucide-react';
import {stations} from './lib/workshop';
import {lunchInfo} from './lib/schedule';
type Day={staff_id:string,presence:string,station:string|null,confirmed:string|null,slots?:{start:string,end:string}[]};
export function CarLift({rotate=false}:{rotate?:boolean}){return <svg className={'car-lift'+(rotate?' rotated-lift':'')} viewBox="0 0 160 92" fill="none" aria-hidden="true"><path d="M20 15v62M140 15v62" stroke="currentColor" strokeWidth="8" strokeLinecap="round"/><path d="M24 27l34 9m-34 29 34-9m78-29-34 9m34 29-34-9" stroke="currentColor" strokeWidth="4"/><rect x="53" y="9" width="54" height="74" rx="17" fill="var(--car-fill,#e2ebee)" stroke="currentColor" strokeWidth="2"/><path d="M61 28q19-7 38 0l-3 15H64zM63 63h34l-2 11H65z" fill="var(--glass-fill,#fff)" stroke="currentColor" strokeWidth="1.5"/><path d="M60 47v12m40-12v12M48 24v13m64-13v13M48 57v13m64-13v13" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/></svg>}
export default function WorkshopPlan({staff,days,date,now,editable,onSelect}:{staff:{id:string,name:string}[],days:Day[],date:string,now:Date,editable:boolean,onSelect:(id:string)=>void}){
 const content=(s:typeof stations[number],i:number)=>{
 const members=days.filter(d=>d.presence==='present'&&d.station===s.id);const office=s.id==='organisation'||s.id==='devis';
 return <><div className="bay-caption"><span>{String(i+1).padStart(2,'0')}</span><strong>{s.short}</strong></div><div className="bay-drawing">{office?<Monitor size={44} strokeWidth={1.4}/>:<CarLift rotate={['pneus1','attelage','vidange1','vidange2','mecalegere','mecalourde','distribution'].includes(s.id)}/>}</div><div className="bay-members">{members.length?members.map(d=>{const lunch=lunchInfo(d,date,now).current;return <span className={'bay-member '+(lunch?'at-lunch':'')} key={d.staff_id}><span>{staff.find(p=>p.id===d.staff_id)?.name||'Collaborateur'}</span>{lunch?<small><Utensils size={12}/> Déjeuner · retour {lunch.end}</small>:d.confirmed?<small><Check size={12}/> Présence confirmée</small>:<small>Affectation prévue</small>}</span>}):<span className="bay-empty">{editable?'+ Affecter':'Sans affectation'}</span>}</div></>};
 return <section className="panel atelier-map"><div className="panel-head"><div><div className="eyebrow">VUE D’ENSEMBLE</div><h2>Le plan de l’atelier</h2><p className="muted">{editable?'Sélectionne un poste pour affecter un collaborateur.':'Les affectations de toute l’équipe, en lecture seule.'}</p></div><span className="subtle-tag">10 ponts · 2 espaces de gestion</span></div><div className="map-legend"><span><i className="legend-dot assigned"/> Affecté</span><span><i className="legend-dot lunch"/> En coupure déjeuner</span><span><Check size={14}/> Présence confirmée</span></div><p className="map-mobile-hint">Fais glisser le plan vers la gauche pour voir les autres postes.</p><div className="atelier-map-scroll"><div className="atelier-grid"><div className="circulation"><span>ZONE DE CIRCULATION</span><small>Plan schématique · ponts aux mêmes dimensions</small></div>{stations.map((s,i)=>{const className='bay '+(s.id==='organisation'||s.id==='devis'?'office ':'')+(days.some(d=>d.presence==='present'&&d.station===s.id)?'has-members':'');const style={gridColumn:s.col,gridRow:s.row};return editable?<button className={className} style={style} key={s.id} onClick={()=>onSelect(s.id)} aria-label={'Affectations : '+s.name}>{content(s,i)}</button>:<article className={className} style={style} key={s.id} aria-label={s.name}>{content(s,i)}</article>})}</div></div><div className="map-footnote">La coupure est déduite des horaires prévus. L’affectation reste visible pendant le déjeuner.</div></section>
}
