'use client';
import { lazy,Suspense,useCallback,useEffect,useState,useRef } from 'react';
import {loadWorkshop,mutateWorkshop,logout,provisionAccount} from '@/lib/supabase';
import { Wrench,Users,Map,ClipboardList,Plus,Check,ChevronLeft,ChevronRight,Download,RefreshCw,CalendarDays,UserCheck,Clock,AlertCircle,Smartphone,Settings2,LogOut,Trash2,Utensils,Megaphone } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Toaster,toast } from 'sonner';
import { stations,parisToday,presenceLabels,priorityLabels } from '@/lib/workshop';
import {ProfileDialog,AnnouncementDialog,type Announcement} from './profile-announcement';
import WorkshopPlan from './workshop-plan';
import {lunchInfo} from './lib/schedule';
const PlanningImport=lazy(()=>import('./planning-import'));
type Staff={id:string,name:string,email?:string,team?:string|null,role?:'employee'|'moderator'};
type Day={staff_id:string,presence:string,station:string|null,confirmed:string|null,slots?:{start:string,end:string}[]};
type Task={id:string,title:string,details:string,staff_id:string,due:string,priority:string,done:number,completed_at:string|null};
type Data={admin:boolean,manager?:boolean,role?:string,user:string,self:string|null,staff:Staff[],days:Day[],tasks:Task[],setup?:boolean,profile?:{photo:string|null},announcement?:Announcement};
function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
const teams=['Technicien services rapide','Electrotechnicien','Mécatronicien','Mécanicien','Encadrants'];
const initials=(name:string)=>name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
const prettyDate=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long'});
export default function Workshop(){
 const [date,setDate]=useState(parisToday),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState('plan'),[mode,setMode]=useState('admin'),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState<'task'|'staff'|'install'|'account'|null>(null),[editing,setEditing]=useState<Staff|null>(null),[taskEdit,setTaskEdit]=useState<Task|null>(null),[taskStaff,setTaskStaff]=useState(''),[priority,setPriority]=useState('normal'),[filter,setFilter]=useState('open'),[install,setInstall]=useState<any>(null),[synced,setSynced]=useState('');
 const [staffRole,setStaffRole]=useState('employee'),[now,setNow]=useState(()=>new Date());
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),15000);return()=>clearInterval(id)},[]);
 const [showProfile,setShowProfile]=useState(false),[showAnnouncement,setShowAnnouncement]=useState(false);
 const [showImport,setShowImport]=useState(false);
 const [teamFilter,setTeamFilter]=useState('all'),[staffTeam,setStaffTeam]=useState('none');
 const requestId=useRef(0);
 const load=useCallback(async(quiet=false)=>{const current=++requestId.current;if(!quiet){setLoading(true);setData(null);}try{const d:any=await loadWorkshop(date);if(current!==requestId.current)return;setData(d);setError('');setSynced(new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}));return d;}catch(e:any){if(current===requestId.current){setData(null);setError(e.message||'Connexion indisponible.');}}finally{if(current===requestId.current)setLoading(false)}},[date]);
 useEffect(()=>{if(data&&!data.setup&&!data.admin&&!data.manager){setMode('employee');setTab(t=>t==='plan'?'journee':t)}},[data?.admin,data?.manager,data?.setup]);
 useEffect(()=>{load();const id=setInterval(()=>load(true),20000);return()=>clearInterval(id)},[load]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const f=(e:any)=>{e.preventDefault();setInstall(e)};window.addEventListener('beforeinstallprompt',f);return()=>window.removeEventListener('beforeinstallprompt',f)},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_workshop_day',title:'Consulter la journée',description:'Lire les postes, présences et tâches affichés pour la date sélectionnée.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Aucun paramètre attendu');const d=await load(true);if(!d)throw Error('Chargement impossible');return {date,days:d.days,tasks:d.tasks}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[load,date]);
 async function action(payload:any,message:string){if(busy)return false;setBusy(true);try{await mutateWorkshop(payload);await load(true);toast.success(message);return true}catch(e:any){toast.error(e.message);return false}finally{setBusy(false)}}
 function moveDate(n:number){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);setDate(d.toLocaleDateString('en-CA'))}
 const manage=!!(data?.admin||data?.manager)&&mode==='admin';
 const admin=!!data?.admin&&mode==='admin';
 const staff=data?.staff||[],days=data?.days||[],tasks=data?.tasks||[];
 const teamStaff=staff.filter(s=>teamFilter==='all'||(teamFilter==='none'?!s.team:s.team===teamFilter));
 const dayFor=(id:string):Day=>days.find(d=>d.staff_id===id)||{staff_id:id,presence:'unknown',station:null,confirmed:null};
 const self=staff.find(s=>s.id===data?.self),selfDay=self?dayFor(self.id):null;
 const visibleTasks=manage?tasks:tasks.filter(t=>t.staff_id===data?.self);
 const openTasks=visibleTasks.filter(t=>!t.done),present=days.filter(d=>d.presence==='present'),confirmed=days.filter(d=>d.confirmed);
 const chosen=stations.find(s=>s.id===selected);
 function taskModal(task?:Task){setTaskEdit(task||null);setTaskStaff(task?.staff_id||staff[0]?.id||'');setPriority(task?.priority||'normal');setModal('task')}
 function setDay(id:string,presence:string,station:string|null){action({action:'day',date,id,presence,station},'Affectation enregistrée')}
 return <div className="app-shell"><Toaster position="top-center" richColors/><header className="topbar"><button type="button" className="brand profile-brand" aria-label="Ouvrir mon profil" onClick={()=>setShowProfile(true)} disabled={!data}><span className="brand-mark"><Wrench size={22}/></span><span><span className="brand-name">Atelier Fayet 33</span><span className="brand-sub">ÉQUIPE & ORGANISATION</span></span></button><div className="top-actions"><span className="desktop-only muted">{data?.user}</span><button className="icon-btn" aria-label="Installer l’application" onClick={()=>setModal('install')}><Download size={19}/></button><button className="icon-btn" onClick={()=>logout().catch(e=>toast.error(e.message))} aria-label="Déconnexion"><LogOut size={18}/></button><button className="avatar owner profile-avatar" disabled={!data} aria-label="Mon profil" onClick={()=>setShowProfile(true)}>{data?.profile?.photo?<img className="header-photo" src={data.profile.photo} alt=""/>:initials(self?.name||data?.user||'AE')}</button></div></header>
 {data?.announcement?.enabled&&data.announcement.message&&<section className="announcement-banner global-announcement" aria-label="Annonce de l’atelier"><Megaphone size={24}/><p>{data.announcement.message}</p>{admin&&<button onClick={()=>setShowAnnouncement(true)} aria-label="Modifier l’annonce"><Settings2 size={18}/><span>Modifier</span></button>}</section>}
 <main><div className="page-heading"><div><div className="eyebrow">L’ATELIER AU QUOTIDIEN</div><h1>{manage?'Une place pour chacun.':'Ma journée à l’atelier.'}</h1><p className="muted">{manage?'Organise les postes, accompagne ton équipe.':'Ton poste, tes priorités et tes tâches.'}</p></div>{(data?.admin||data?.manager)&&<Tabs value={mode} onValueChange={v=>{setMode(v);setTab(v==='admin'?'plan':'journee')}}><TabsList className="mode-tabs"><TabsTrigger value="admin">{data?.admin?'Administration':'Modération'}</TabsTrigger><TabsTrigger value="employee"><Smartphone size={16}/> Collaborateur</TabsTrigger></TabsList></Tabs>}</div>
 {error&&<div className="error-banner" role="alert"><AlertCircle size={20}/><span>{error}</span><button onClick={()=>load()}>Réessayer</button></div>}
 {!data&&loading&&<div className="empty large"><RefreshCw className="spin"/> Chargement de l’atelier…</div>}
 {data&&<>
 <div className={manage?"summary-grid":"summary-grid collaborator-summary"}>{manage&&<><div className="stat"><span className="stat-icon"><Users size={21}/></span><div><strong>{present.length}<small> / {staff.length}</small></strong><span>Collaborateurs présents</span></div></div><div className="stat"><span className="stat-icon green"><UserCheck size={21}/></span><div><strong>{confirmed.length}</strong><span>Présences confirmées</span></div></div></>}<div className="stat"><span className="stat-icon blue"><ClipboardList size={21}/></span><div><strong>{openTasks.length}</strong><span>Tâches à terminer</span></div></div><div className="stat"><span className="stat-icon orange"><Clock size={21}/></span><div><strong>{openTasks.filter(t=>t.priority==='urgent'||t.due<parisToday()).length}</strong><span>Urgentes ou en retard</span></div></div></div>
 {admin&&<div className="import-launch"><button className="secondary" onClick={()=>setShowAnnouncement(true)}><Megaphone size={18}/> Gérer l’annonce</button><button className="secondary" onClick={()=>setShowImport(true)}><CalendarDays size={18}/> Importer un planning PDF</button></div>}
 <div className="workspace-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList className="nav-tabs">{!manage&&<TabsTrigger value="journee"><UserCheck size={18}/> Ma journée</TabsTrigger>}<TabsTrigger value="plan"><Map size={18}/> Plan de l’atelier</TabsTrigger><TabsTrigger value="tasks"><ClipboardList size={18}/> Tâches <span className="count">{openTasks.length}</span></TabsTrigger>{admin&&<TabsTrigger value="team"><Users size={18}/> Équipes</TabsTrigger>}</TabsList></Tabs><div className="date-control"><button className="icon-btn" onClick={()=>moveDate(-1)} aria-label="Jour précédent"><ChevronLeft size={18}/></button><CalendarDays size={17}/><input type="date" aria-label="Jour affiché" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/><button className="icon-btn" onClick={()=>moveDate(1)} aria-label="Jour suivant"><ChevronRight size={18}/></button><button className="today" onClick={()=>setDate(parisToday())}>Aujourd’hui</button></div></div>
 {manage&&(tab==='team'||tab==='plan')&&<div className="teams-toolbar"><label>Équipe affichée<Choice label="Filtrer les collaborateurs par équipe" value={teamFilter} onChange={setTeamFilter} options={[{value:'all',label:`Toutes les équipes (${staff.length})`},...teams.map(t=>({value:t,label:`${t} (${staff.filter(s=>s.team===t).length})`})),{value:'none',label:`Sans équipe (${staff.filter(s=>!s.team).length})`}]}/></label><p className="muted">{teamStaff.length} collaborateur(s){tab==='plan'?' dans la liste · le plan affiche tous les postes':''}</p></div>}
 {tab==='plan'&&<div className={manage?'plan-layout':'plan-readonly'}><WorkshopPlan staff={staff} days={days} date={date} now={now} editable={manage} onSelect={setSelected}/>{manage&&<aside className="panel roster-panel"><div className="panel-head"><div><h2>L’équipe du jour</h2><p className="muted">{present.filter(d=>!d.station).length} présent(s) à affecter</p></div><Users size={20}/></div><p className="roster-help">{admin?'Renseigne les présences, puis sélectionne un poste sur le plan.':'Sélectionne un poste pour déplacer un collaborateur prévu présent.'}</p><div className="roster">{!teamStaff.length&&<p className="team-empty">Aucun collaborateur dans cette équipe.</p>}{teamStaff.map(s=>{const d=dayFor(s.id);return <div className="person-row" key={s.id}><div className="person-top"><span className={'avatar c'+(+s.id%4)}>{initials(s.name)}</span><div><strong>{s.name}</strong><span className="person-team">{s.team||'Sans équipe'}</span><span className="muted">{stations.find(x=>x.id===d.station)?.name||'Sans affectation'}</span>{!!d.slots?.length&&<span className="day-slots">{d.slots.map(t=>t.start+'–'+t.end).join(' · ')}</span>}</div><LunchBadge day={d} date={date} now={now}/>{d.confirmed&&<Check className="confirmed" size={18}/>}</div>{admin?<Choice label={'Présence de '+s.name} value={d.presence} options={Object.entries(presenceLabels).map(([value,label])=>({value,label}))} onChange={v=>setDay(s.id,v,v==='present'?d.station:null)}/>:<span className="subtle-tag">{presenceLabels[d.presence]}</span>}</div>})}</div></aside>}</div>}
 {admin&&tab==='team'&&<section className="panel"><div className="panel-head"><div><h2>Équipes et collaborateurs</h2><p className="muted">Une équipe métier par collaborateur, modifiable dans sa fiche.</p></div><button className="primary" onClick={()=>{setEditing(null);setStaffTeam('none');setStaffRole('employee');setModal('staff')}}><Plus size={18}/> Ajouter un collaborateur</button></div><div className="info-line"><AlertCircle size={18}/>Seules les adresses e-mail renseignées ici ont accès aux données de l’atelier. Crée les identifiants depuis sa fiche et transmets-les au collaborateur.</div><div className="team-grid">{!teamStaff.length&&<p className="team-empty">Aucun collaborateur dans cette équipe. Sélectionne « Toutes les équipes », puis modifie une fiche pour lui attribuer une équipe.</p>}{teamStaff.map(s=><div className="team-card" key={s.id}><span className={'avatar c'+(+s.id%4)}>{initials(s.name)}</span><h3>{s.name}</h3><span className="team-badge">{s.team||'Sans équipe'}</span><span className="role-badge">{s.email==='nchivot@norauto.fr'?'Administrateur':s.role==='moderator'?'Modérateur':'Collaborateur'}</span><p className="muted">{s.email||'Adresse e-mail à renseigner'}</p><button className="secondary" onClick={()=>{setEditing(s);setStaffTeam(s.team||'none');setStaffRole(s.role||'employee');setModal('staff')}}><Settings2 size={16}/> Modifier la fiche</button><button className="secondary" disabled={!s.email} onClick={()=>{setEditing(s);setModal('account')}}>Créer / réinitialiser l’accès</button>{s.email!=='nchivot@norauto.fr'&&s.id!==data?.self&&<button className="secondary danger" disabled={busy} onClick={()=>{if(window.confirm(`Supprimer ${s.name} de l’équipe active ? Son accès à l’atelier sera bloqué. Ses tâches et son historique seront archivés et ne seront plus affichés.`))void action({action:'deleteStaff',id:s.id},'Collaborateur retiré de l’équipe')}}><Trash2 size={16}/> Supprimer le collaborateur</button>}</div>)}</div></section>}
 {!manage&&tab==='journee'&&<div className="my-layout"><section className="panel my-station"><div className="eyebrow">MON POSTE · {prettyDate(date)}</div><h2>{self?stations.find(s=>s.id===selfDay?.station)?.name||'Pas encore affecté':'Associe ta fiche collaborateur'}</h2><p>{self?self.name:'Dans l’espace Administration → Équipe, renseigne ton adresse e-mail sur ta fiche pour utiliser cet espace.'}</p>{self&&<><span className="team-badge">{self.team||'Sans équipe'}</span><br/><span className="subtle-tag">{presenceLabels[selfDay?.presence||'unknown']}</span>{!!selfDay?.slots?.length&&<p className="my-hours"><strong>Mes horaires prévus</strong><br/>{selfDay.slots.map(t=>t.start+'–'+t.end).join(' · ')}</p>}<LunchBadge day={selfDay} date={date} now={now}/><p className="muted">{selfDay?.confirmed?'Ta présence à ce poste est confirmée.':'Confirme ta présence une fois arrivé à ton poste.'}</p><button className="primary" disabled={busy||date!==parisToday()||!selfDay?.station||!!selfDay?.confirmed} onClick={()=>action({action:'confirm'},'Présence confirmée')}><UserCheck size={18}/>{selfDay?.confirmed?'Présence confirmée':'Je suis à mon poste'}</button>{date!==parisToday()&&<p className="muted">La confirmation est disponible pour aujourd’hui uniquement.</p>}</>}</section><section className="panel"><div className="panel-head"><div><h2>Mes priorités</h2><p className="muted">Les prochaines tâches à terminer</p></div></div><div className="task-list">{openTasks.slice(0,5).map(t=><TaskCard key={t.id} task={t} name={self?.name||''} busy={busy} onComplete={()=>action({action:'complete',id:t.id,done:true},'Tâche terminée')} />)}{!openTasks.length&&<div className="empty"><Check/><h3>Aucune tâche en attente</h3><p>Tes tâches apparaîtront ici quand elles te seront attribuées.</p></div>}</div></section></div>}
 {tab==='tasks'&&<section className="panel"><div className="panel-head"><div><h2>{manage?'Les tâches de l’équipe':'Mes tâches'}</h2><p className="muted">Toutes les échéances · {openTasks.length} tâche(s) en cours</p></div>{manage&&<button className="primary" onClick={()=>taskModal()}><Plus size={18}/> Nouvelle tâche</button>}</div><div className="task-filters"><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="open">À faire</TabsTrigger><TabsTrigger value="urgent">Urgentes</TabsTrigger><TabsTrigger value="done">Terminées</TabsTrigger></TabsList></Tabs></div><div className="task-list">{visibleTasks.filter(t=>filter==='done'?!!t.done:filter==='urgent'?!t.done&&(t.priority==='urgent'||t.due<parisToday()):!t.done).sort((a,b)=>(a.due.localeCompare(b.due))||(['urgent','high','normal'].indexOf(a.priority)-['urgent','high','normal'].indexOf(b.priority))).map(t=><TaskCard key={t.id} task={t} name={staff.find(s=>s.id===t.staff_id)?.name||''} busy={busy} onComplete={()=>action({action:'complete',id:t.id,done:!t.done},t.done?'Tâche rouverte':'Tâche terminée')} canComplete={!!data?.admin||t.staff_id===data?.self} onEdit={manage?()=>taskModal(t):undefined} onDelete={manage?()=>{if(window.confirm(`Supprimer définitivement la tâche « ${t.title} » ?`))void action({action:'deleteTask',id:t.id},'Tâche supprimée')}:undefined}/>)}{!visibleTasks.some(t=>filter==='done'?!!t.done:filter==='urgent'?!t.done&&(t.priority==='urgent'||t.due<parisToday()):!t.done)&&<div className="empty"><ClipboardList size={34}/><h3>{filter==='done'?'Aucune tâche terminée':filter==='urgent'?'Aucune urgence':'Tout est à jour'}</h3><p>{manage?'Crée une tâche pour l’attribuer à un collaborateur.':'Les tâches qui te sont attribuées apparaîtront ici.'}</p>{manage&&filter==='open'&&<button className="secondary" onClick={()=>taskModal()}>Créer la première tâche</button>}</div>}</div></section>}
 <footer><span>ATELIER FAYET 33</span><button onClick={()=>load(true)}><RefreshCw size={13}/> {error?'Connexion à rétablir':`Actualisé à ${synced} · toutes les 20 s`}</button></footer>
 </>}
 </main>
 {showProfile&&data&&<ProfileDialog name={self?.name||'Mon compte'} email={data.user} team={self?.team} role={data.role||(data.admin?'admin':'employee')} photo={data.profile?.photo} onClose={()=>setShowProfile(false)} onSaved={()=>load(true)}/>}
 {showAnnouncement&&admin&&<AnnouncementDialog announcement={data?.announcement} onClose={()=>setShowAnnouncement(false)} onSaved={()=>load(true)}/>}
 {showImport&&admin&&<Suspense fallback={<div className="import-loading">Chargement du lecteur PDF…</div>}><PlanningImport staff={staff} onClose={()=>setShowImport(false)} onImported={()=>{void load(true)}}/></Suspense>}
 <Dialog open={!!selected&&manage} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="app-dialog"><DialogTitle>{chosen?.name}</DialogTitle><DialogDescription>Affectations du {prettyDate(date)}. Plusieurs collaborateurs peuvent partager ce poste.</DialogDescription><div className="assignment-list">{staff.map(s=>{const d=dayFor(s.id);return <div className="assignment-row" key={s.id}><span className={'avatar c'+(+s.id%4)}>{initials(s.name)}</span><div><strong>{s.name}</strong><small>{s.team||'Sans équipe'}</small><small>{presenceLabels[d.presence]}{d.station?' · '+stations.find(x=>x.id===d.station)?.name:''}</small></div><button className={d.station===selected?'secondary':'primary'} disabled={busy||d.presence!=='present'} onClick={()=>setDay(s.id,'present',d.station===selected?null:selected)}>{d.station===selected?'Retirer':'Affecter'}</button></div>})}</div><p className="muted">Les absents et les présences non renseignées ne peuvent pas être affectés.</p></DialogContent></Dialog>
 <Dialog open={!!modal} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="app-dialog"><DialogTitle>{modal==='task'?(taskEdit?'Modifier la tâche':'Nouvelle tâche'):modal==='staff'?(editing?'Fiche collaborateur':'Ajouter un collaborateur'):modal==='account'?'Identifiants du collaborateur':'Installer Atelier Fayet 33 sur ton téléphone'}</DialogTitle><DialogDescription>{modal==='task'?'Une consigne claire, un responsable et une échéance.':modal==='staff'?'L’adresse e-mail identifie le compte autorisé à utiliser cette fiche.':modal==='account'?'Crée le compte ou remplace son mot de passe existant, puis transmets les identifiants au collaborateur.':'Une icône sur ton écran d’accueil, pour retrouver ton atelier rapidement.'}</DialogDescription>
 {modal==='task'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await action({action:taskEdit?'editTask':'task',id:taskEdit?.id,title:f.get('title'),details:f.get('details'),due:f.get('due'),staffId:taskStaff,priority},'Tâche enregistrée'))setModal(null)}}><label>Intitulé<input name="title" required maxLength={200} defaultValue={taskEdit?.title} placeholder="Ex. Ranger et contrôler l’outillage"/></label><label>Consignes<textarea name="details" maxLength={4000} defaultValue={taskEdit?.details} placeholder="Informations utiles pour réaliser la tâche" rows={3}/></label><label>Collaborateur<Choice label="Collaborateur responsable" value={taskStaff} onChange={setTaskStaff} options={staff.map(s=>({value:s.id,label:s.name}))}/></label><div className="form-cols"><label>Échéance<input type="date" name="due" required defaultValue={taskEdit?.due||date}/></label><label>Priorité<Choice label="Priorité" value={priority} onChange={setPriority} options={Object.entries(priorityLabels).map(([value,label])=>({value,label}))}/></label></div><button className="primary full" disabled={busy}>{busy?'Enregistrement…':'Enregistrer la tâche'}</button></form>}
 {modal==='staff'&&admin&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await action({action:editing?'staff':'createStaff',id:editing?.id,role:staffRole,name:f.get('name'),email:f.get('email'),team:staffTeam==='none'?null:staffTeam},'Fiche enregistrée'))setModal(null)}}><label>Nom du collaborateur<input name="name" required maxLength={100} defaultValue={editing?.name}/></label><label>Adresse e-mail du compte de connexion<input name="email" type="email" defaultValue={editing?.email||''} readOnly={editing?.email==='nchivot@norauto.fr'} placeholder="prenom@exemple.fr"/></label><label>Équipe<Choice label="Équipe du collaborateur" value={staffTeam} onChange={setStaffTeam} options={[{value:"none",label:"Sans équipe"},...teams.map(t=>({value:t,label:t}))]}/></label>{editing?.email==='nchivot@norauto.fr'?<p className="role-badge">Administrateur · droits conservés</p>:<label>Rôle dans l’application<Choice label="Rôle du collaborateur" value={staffRole} onChange={setStaffRole} options={[{value:'employee',label:'Collaborateur'},{value:'moderator',label:'Modérateur'}]}/></label>}<p className="muted">Un modérateur peut gérer les affectations et les tâches. Seul l’administrateur gère les fiches, les rôles, les présences prévues et les imports.</p><p className="muted">Chaque adresse doit être unique. Le collaborateur ne pourra valider que ses propres tâches et sa présence.</p><button className="primary full" disabled={busy}>Enregistrer la fiche</button></form>}
 {modal==='account'&&editing&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);try{const result=await provisionAccount(editing.id,String(f.get('password')));toast.success(result.created?'Compte créé. Tu peux transmettre les identifiants.':'Mot de passe remplacé. Transmets le nouveau mot de passe.');setModal(null)}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}><p><strong>{editing.name}</strong><br/>{editing.email}</p><label>Nouveau mot de passe<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><p className="muted">12 caractères minimum. Conserve le mot de passe avant de valider : il ne sera pas réaffiché. Si un compte existe déjà pour cette adresse, son mot de passe sera remplacé.</p><button className="primary full" disabled={busy}>{busy?'Enregistrement…':'Créer / réinitialiser l’accès'}</button></form>}
 {modal==='install'&&<div className="install-content">{install&&<button className="primary full" onClick={async()=>{await install.prompt();const result=await install.userChoice;if(result.outcome==='accepted')setModal(null);setInstall(null)}}><Download size={18}/> Installer l’application</button>}<div><h3>Sur iPhone</h3><p>Ouvre le lien dans Safari, puis utilise Partager → Sur l’écran d’accueil.</p></div><div><h3>Sur Android</h3><p>Ouvre le lien dans Chrome, puis utilise le menu → Installer l’application ou Ajouter à l’écran d’accueil.</p></div><p className="muted">Une connexion Internet est nécessaire pour consulter et enregistrer les données. Connecte-toi avec le compte de connexion associé à ta fiche.</p></div>}
 </DialogContent></Dialog>
 </div>
}
function TaskCard({task:t,name,busy,onComplete,onEdit,onDelete,canComplete=true}:{task:Task,name:string,busy:boolean,onComplete:()=>void,onEdit?:()=>void,onDelete?:()=>void,canComplete?:boolean}){return <article className={'task-card '+(t.done?'done':'')}><button className={'task-check '+(t.done?'checked':'')} disabled={busy||!canComplete} onClick={onComplete} aria-label={t.done?'Rouvrir '+t.title:'Terminer '+t.title}>{t.done&&<Check size={18}/>}</button><div className="task-body"><div className="task-title"><h3>{t.title}</h3><span className={'priority '+t.priority}>{priorityLabels[t.priority]}</span></div>{t.details&&<p className="task-details">{t.details}</p>}<div className="task-meta"><span><Users size={14}/> {name}</span><span className={!t.done&&t.due<parisToday()?'late':''}><CalendarDays size={14}/> {prettyDate(t.due)} {!t.done&&t.due<parisToday()&&'· En retard'}</span>{t.completed_at&&<span><Check size={14}/> Terminée le {new Date(t.completed_at).toLocaleDateString('fr-FR')}</span>}</div></div>{onEdit&&<button className="icon-btn" onClick={onEdit} aria-label={'Modifier '+t.title}><Settings2 size={18}/></button>}{onDelete&&<button className="icon-btn danger" disabled={busy} onClick={onDelete} aria-label={'Supprimer '+t.title}><Trash2 size={18}/></button>}</article>}

function LunchBadge({day,date,now}:{day:Day|null|undefined,date:string,now:Date}){const info=lunchInfo(day,date,now);if(!info.breaks.length)return null;return <span className={'lunch-badge '+(info.current?'live':'')}><Utensils size={14}/>{info.current?`En coupure déjeuner · retour ${info.current.end}`:`Déjeuner prévu : ${info.breaks.map(b=>b.start+'–'+b.end).join(' · ')}`}</span>}
